; VIDEO.INC
;
; Adapted from the work of Jerome Shidel INFO.PAS.
;
; Copyright 1990-2015, Jerome Shidel.
;   
; This project and related files are subject to the terms of the Mozilla 
; Public License,  v. 2.0. If a copy of the MPL was not distributed with 
; this file, You can obtain one at http://mozilla.org/MPL/2.0/.
;

VIDEO_CARD_VESA    EQU 9
VIDEO_CARD_VGA     EQU 8
VIDEO_CARD_MCGA    EQU 7
VIDEO_CARD_EGA     EQU 6
VIDEO_CARD_CGA     EQU 5
VIDEO_CARD_INCOLOR EQU 4
VIDEO_CARD_HGCPLUS EQU 3
VIDEO_CARD_HGC     EQU 2
VIDEO_CARD_MDA     EQU 1
